name: "Publish Bicep Modules to ACR"
description: "Publishes Bicep modules to Azure Container Registry (ACR)"

inputs:
  acr_name:
    description: "The name of the Azure Container Registry (ACR) to publish to"
    required: true
  base_module_path:
    description: "Base path for modules (e.g., elements/res/network/network-security-group)"
    required: true
  version:
    description: "Version tag for the Bicep module (e.g., 1.0.0)"
    required: true

outputs:
  publish_status:
    description: "Status of the publish operation"
    value: ${{ env.publish_status }}

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install or Update Bicep CLI
      shell: bash
      run: |
        az bicep install
        az bicep upgrade

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false
        environment: azurecloud
        auth-type: SERVICE_PRINCIPAL

    - name: Publish Bicep Modules
      env:
        ACR_NAME: ${{ inputs.acr_name }}
        BASE_MODULE_PATH: ${{ inputs.base_module_path }}
        VERSION: ${{ inputs.version }}
      shell: bash
      run: |
        # Find all main.bicep files in the specified directory structure
        find "$BASE_MODULE_PATH" -type f -name "main.bicep" | while read -r BICEP_FILE; do
          MODULE_DIR=$(dirname "$BICEP_FILE")
          echo "Publishing module at path: $MODULE_DIR"
          # Publish the Bicep file to ACR with the directory structure and version
          az bicep publish \
            --file "$BICEP_FILE" \
            --target "br:$ACR_NAME.azurecr.io/$MODULE_DIR:$VERSION"
        done

    - name: Set publish status
      shell: bash
      run: echo "publish_status=success" >> "$GITHUB_ENV"
