name: "Publish Bicep Modules to ACR"
description: "Publishes Bicep modules to Azure Container Registry (ACR)"

inputs:
  acr_name:
    description: "The name of the Azure Container Registry (ACR) to publish to"
    required: true
  base_module_path:
    description: "Base path for modules (e.g., elements/res/network/network-security-group)"
    required: true
  version:
    description: "Version tag for the Bicep module (e.g., 1.0.0)"
    required: true
  azure_client_id:
    description: "Az Auth: Azure client ID"
    required: true
  azure_tenant_id:
    description: "Az Auth: Azure tenant ID"
    required: true
  azure_subscription_id:
    description: "Az Auth: Azure subscription ID"
    required: true

outputs:
  publish_status:
    description: "Status of the publish operation"
    value: ${{ env.publish_status }}

runs:
  using: "composite"
  steps:
    - name: Install or Update Bicep CLI
      shell: bash
      run: |
        az bicep install
        az bicep upgrade

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
        enable-AzPSSession: true

    - name: Publish Bicep Modules
      env:
        ACR_NAME: ${{ inputs.acr_name }}
        BASE_MODULE_PATH: ${{ inputs.base_module_path }}
        VERSION: ${{ inputs.version }}
      shell: pwsh
      run: |
        # Split the version into its components
        $versionComponents = $env:VERSION -split '\.'
        $majorVersion = [int]$versionComponents[0]
        $minorVersion = [int]$versionComponents[1]
        $patchVersion = [int]$versionComponents[2]

        # Increment the patch version
        $newPatchVersion = $patchVersion + 1
        $newVersion = "$majorVersion.$minorVersion.$newPatchVersion"

        Write-Output "Incremented version to: $newVersion"

        # Find all main.bicep files in the specified directory structure
        Get-ChildItem -Path $env:BASE_MODULE_PATH -Recurse -Filter "main.bicep" | ForEach-Object {
            $bicepFile = $_.FullName
            Write-Output "Publishing module at path: $BASE_MODULE_PATH"

            # Publish the Bicep file to ACR with the directory structure and version
            az bicep publish --file $bicepFile --target "br:$($env:ACR_NAME).azurecr.io/$($BASE_MODULE_PATH):$($newVersion)" --force
        }

    - name: Set publish status
      shell: bash
      run: echo "publish_status=success" >> "$GITHUB_ENV"

