name: "Deploy Bicep Template"
description: "Deploy a Bicep template to Azure and output the resource group name"

inputs:
  module_name:
    description: "Specify the module path (e.g., avm/res/network/network-security-group)"
    required: true
  test_subdir:
    description: "Specify the test subdirectory (e.g., tests/e2e/defaults)"
    required: true
  file_name:
    description: "Specify the Bicep file name"
    required: true
    default: "main.test.bicep"
  region:
    description: "Deployment region (e.g., westeurope)"
    required: false
    default: "westeurope"
  azure_client_id:
    description: "Az Auth: Azure client ID"
    required: true
  azure_tenant_id:
    description: "Az Auth: Azure tenant ID"
    required: true
  azure_subscription_id:
    description: "Az Auth: Azure subscription ID"
    required: true

outputs:
  deployed_rg_name:
    description: "The name of the deployed resource group"
    value: ${{ env.deployed_rg_name }}

runs:
  using: "composite"
  steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
        enable-AzPSSession: true

    - name: Deploy Bicep Template
      id: deploy_bicep
      shell: pwsh
      env:
        TEMPLATE_PATH: "${{ inputs.module_name }}/${{ inputs.test_subdir }}/${{ inputs.file_name }}"
        DEPLOY_REGION: ${{ inputs.region }}
      run: |
        Write-Output "Deploying Bicep template using path: $env:TEMPLATE_PATH"

        $deploymentOutput = az deployment sub create --location "$env:DEPLOY_REGION" --template-file "${{ github.workspace }}/$env:TEMPLATE_PATH"
        $RESOURCE_GROUP_NAME = ($deploymentOutput | ConvertFrom-Json).properties.parameters.resourceGroupName.value

        if ($LASTEXITCODE -ne 0) {
          Write-Error "Deployment command failed."
          exit 1
        }

        if ($RESOURCE_GROUP_NAME) {
          Write-Output "Deployed Resource Group Name: $RESOURCE_GROUP_NAME"
          echo "deployed_rg_name=$RESOURCE_GROUP_NAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        } else {
          Write-Error "Deployment failed, no Resource Group created."
          exit 1
        }
    - name: Set output
      run: echo "::set-output name=deployed_rg_name::$env:RESOURCE_GROUP_NAME"


