name: "Remove Resource Group"
description: "Clean up resources deployed for testing"

inputs:
  resource_group_name:
    description: "Resource Group Name to remove"
    required: true
  azure_client_id:
    description: "Az Auth: Azure client ID"
    required: true
  azure_tenant_id:
    description: "Az Auth: Azure tenant ID"
    required: true
  azure_subscription_id:
    description: "Az Auth: Azure subscription ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
        enable-AzPSSession: false
        environment: azurecloud
        auth-type: SERVICE_PRINCIPAL

    - name: Cleanup Resource Group
      shell: bash
      env:
        RESOURCE_GROUP_NAME: ${{ inputs.resource_group_name }}
      run: |
        if [ -n "$RESOURCE_GROUP_NAME" ]; then
          echo "Cleaning up Resource Group: $RESOURCE_GROUP_NAME"
          az group delete --name "$RESOURCE_GROUP_NAME" --yes --no-wait
        else
          echo "No resource group to delete."
        fi
