---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD013:
  line_length: 865 # Line length 80 is far too short
MD034: false # Ordered list item prefix
MD028: false # Allow inline HTML
MD009: false
MD051/link-fragments: false

#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
