name: development-workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'feature/onboard-avm/**'
  push:
    branches:
      - 'feature/onboard-avm/**'

permissions:
      id-token: write
      contents: read

jobs:
      pull-request-workflow:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        environment: sandbox
        steps:
          - name: Checkout the feature branch
            uses: actions/checkout@v4
            with:
              ref: ${{ github.head_ref }}
              clean: true

          - name: Debug - List Directory Contents
            run: |
                echo "Listing workspace directory:"
                ls -R "${{ github.workspace }}"

      development-commit-workflow:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        environment: sandbox
        steps:
          - name: Checkout the feature branch
            uses: actions/checkout@v4
            with:
              ref: ${{ github.head_ref }}
              clean: true

          - name: Debug - List Directory Contents
            run: |
                echo "Listing workspace directory:"
                ls -R "${{ github.workspace }}"