name: development-workflow

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        type: boolean
        description: "Remove deployed module"
        required: false
        default: true
  push:
    branches:
      - "feature/onboard-avm/**"
    paths:
      - "elements/res/**"
      - ".github/workflows/development-workflow.yml"
      - "!utilities/**"
      - "!*/**/README.md"

permissions:
  id-token: write
  contents: read
  statuses: write

jobs:
  Lint-Test-Deploy-job:
    runs-on: ubuntu-latest
    environment: sandbox
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Extract module name and version from branch
        id: extract_vars
        run: |
          BRANCH_NAME="${{ env.BRANCH_NAME }}"
          MODULE_NAME=$(echo "$BRANCH_NAME" | sed -E 's|feature/onboard-avm/(.+)-[0-9]+\.[0-9]+\.[0-9]+|\1|')
          VERSION=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Extracted MODULE_NAME: $MODULE_NAME"
          echo "Extracted VERSION: $VERSION"
          echo "module_name=elements/${MODULE_NAME}" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Checkout the feature branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: What-If Validation Template
        uses: ./.github/actions/templates/validation
        with:
          module_name: ${{ env.module_name }}
          id: Validation
          test_subdir: "tests/e2e/defaults"
          file_name: "main.test.bicep"
          region: "centralindia"
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep Template
        id: Deploy
        uses: ./.github/actions/templates/deploy
        with:
          module_name: ${{ env.module_name }}
          test_subdir: "tests/e2e/defaults"
          file_name: "main.test.bicep"
          region: "centralindia"
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
