name: Onboarding Workflow New

on:
  workflow_dispatch:
    inputs:
      module_path:
        description: 'Module path and version'
        required: true
        default: 'network/network-security-group/0.5.0'

jobs:
  onboard_modules:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Define inputs
        id: define_inputs
        shell: pwsh
        run: |
          $moduleInput = "${{ github.event.inputs.module_path }}"
          $moduleParts = $moduleInput -split '/'
          $moduleName = "$($moduleParts[0])/$($moduleParts[1])"
          $branchName = "$moduleInput"
          $version = $moduleParts[2]
          echo "::set-output name=module_name::$moduleName"
          echo "::set-output name=branch_name::$branchName"
          echo "::set-output name=version::$version"

      - name: Create feature branch
        shell: pwsh
        run: |
          git checkout -b "${{ steps.define_inputs.outputs.branch_name }}" origin/main

      - name: Checkout external repository
        uses: actions/checkout@v2
        with:
          repository: your-org/brm-modules
          ref: "refs/tags/avm/res/${{ steps.define_inputs.outputs.module_name }}/${{ steps.define_inputs.outputs.version }}"

      - name: Copy module to new branch
        shell: pwsh
        run: |
          $moduleName = "${{ steps.define_inputs.outputs.module_name }}"
          $sourceDir = "avm/res/$moduleName"
          $branchName = "${{ steps.define_inputs.outputs.branch_name }}"
          $destDir = "elements/res/$moduleName"
          Write-Output "Copying module from: $sourceDir to: $destDir"
          Copy-Item -Path "$sourceDir\*" -Destination "$destDir" -Recurse -Force

      - name: Clean up external repository
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force -Path brm-modules

      - name: Push changes to feature branch
        shell: pwsh
        run: |
          git add .
          git commit -m "Add module ${{ steps.define_inputs.outputs.module_name }} version ${{ steps.define_inputs.outputs.version }}"
          git push origin "${{ steps.define_inputs.outputs.branch_name }}"
