name: Publishing-Workflow

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        type: boolean
        description: "Remove deployed module"
        required: false
        default: true
  pull_request:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read
  statuses: write

env:
  moduleTestSubDir: "tests/e2e/defaults"
  moduleTestFileName: "main.test.bicep"
  elementsRootFolder: "elements/res"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/ci/') == false
    outputs: 
      resourceGroupName: ${{ steps.deploy.outputs.deployed_rg_name }}
    environment: sandbox
    steps:
      - name: Checkout the feature branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Define inputs
        id: define_inputs
        shell: pwsh
        run: |
          # Split the branch name into module name and version
          $moduleParts = "${{ github.ref_name }}" -split '/'
          # Module name
          $moduleName = "$($moduleParts[0])/$($moduleParts[1])"
          # Set the outputs
          echo "::set-output name=module_name::$moduleName"
      - name: Deploy Bicep Test E2E Defaults
        id: deploy
        uses: ./.github/actions/templates/deploy
        with:
          module_name: "${{ steps.define_inputs.outputs.module_name }}"
          test_subdir: "${{ env.moduleTestSubDir }}"
          file_name: "${{ env.moduleTestFileName }}"
          region: ${{ vars.AZURE_RESOURCE_REGION }}
          namePrefix: ${{ vars.AZURE_RESOURCE_PREFIX }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  Publish:
    needs: Deploy
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/ci/') == false
    environment: sandbox
    steps:
      - name: Checkout the feature branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Define inputs
        id: define_inputs
        shell: pwsh
        run: |
          # Split the branch name into module name and version
          $moduleParts = "${{ github.ref_name }}" -split '/'
          # Remove patch version
          $versionParts = $moduleParts[2] -split '\.'
          $majorVersion = [int]$versionParts[0]
          $minorVersion = [int]$versionParts[1]
          $version = "$majorVersion.$minorVersion"
          # Module name
          $moduleName = "$($moduleParts[0])/$($moduleParts[1])"
          # Set the outputs
          echo "::set-output name=module_name::$moduleName"
          echo "::set-output name=version::$version"
      - name: Publish Bicep Modules to ACR      
        uses: ./.github/actions/templates/publish
        with:
          acr_name: ${{ vars.BICEP_ACR_NAME}}
          base_module_path: ${{ env.elementsRootFolder}}/${{ steps.define_inputs.outputs.module_name }}
          version: ${{ steps.define_inputs.outputs.version }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  Removal:
    needs: 
      - Deploy
      - Publish
    runs-on: ubuntu-latest
    environment: sandbox
    if: ${{ github.event.inputs.removeDeployment == 'true' }} && startsWith(github.ref, 'refs/heads/ci/') == false
    steps:
      - name: Checkout the feature branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Test Output
        shell: pwsh
        run: |
          Write-Output "Deployed Resource Group Name: ${{ needs.Deploy.outputs.resourceGroupName }}"
      - name: Remove Deployment
        uses: ./.github/actions/templates/remove
        with:
          resource_group_name: ${{ needs.Deploy.outputs.resourceGroupName }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}