name: test-workflow

on:
  workflow_dispatch:
    inputs:
      remove_deployment:
        type: boolean
        description: "Remove Deployment"
        required: true
        default: true
  pull_request:
    branches:
      - "main"

    
permissions:
  id-token: write
  contents: read
  statuses: write

env:
  moduleTestSubDir: "tests/e2e/defaults"
  moduleTestFileName: "main.test.bicep"
  elementsRootFolder: "elements/res"
  CURRENT_BRANCH_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

jobs:
  Show-Output:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Echo Branch Name
        run:  echo "Current Branch Name $CURRENT_BRANCH_NAME"
      - name: Checkout the feature branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CURRENT_BRANCH_NAME }}
      - name: Echo Branch Name
        run:  echo "Current Branch Name $CURRENT_BRANCH_NAME"
      - name: Deployment Removal Options
        id: check_commit
        shell: pwsh
        run: |
          $trigger = "${{ github.event_name}}"
          switch ($trigger)
          {
            'pull_request'
            {
                $commitMessages = git log --format=%B --no-merges origin/${{ github.event.pull_request.head.ref }}          
                write-host "This is a Pull Request Trigger and Commit Message: $($commitMessages)"
                if ($commitMessages -match 'remove_deployment=false' ) {
                  "remove_deployment=false" | Out-File -FilePath $env:GITHUB_ENV -Append
                } else { "remove_deployment=true" | Out-File -FilePath $env:GITHUB_ENV -Append }
            }
            'workflow_dispatch'
            {
                $workflow_dispatch = "${{ inputs.remove_deployment }}"
                write-host "This is a Workflow Dispatch Trigger and Input Option: $($workflow_dispatch)"
                if($workflow_dispatch -eq 'false') {
                  "remove_deployment=false" | Out-File -FilePath $env:GITHUB_ENV -Append
                } else { "remove_deployment=true" | Out-File -FilePath $env:GITHUB_ENV -Append }
            }
            default { "remove_deployment=true" | Out-File -FilePath $env:GITHUB_ENV -Append }
          }
      - name: Remove Deployment
        if: ${{ env.remove_deployment == true }} 
        run:  echo "Commit check remove_deployment = ${{ env.remove_deployment }}, Workflow_dispatch = ${{ inputs.remove_deployment }}"

